#!/usr/bin/env python2

import sys, itertools, argparse

p = argparse.ArgumentParser(description=
    "nicely format tab-separated data without loading everything into ram")
p.add_argument("-j", "--justify", choices=["left", "right", "center"],
    help="what kind of justification to apply to each column", default="left")
p.add_argument("-i", "--initial", type=int, metavar="rows",
    help="how much stdin to read before starting output", default=100)
args = p.parse_args()

def tsv(instream):
  max_widths = {}
  just = {"left": "ljust", "right": "rjust", "center": "center"}[args.justify]

  def process(instream):
    for row in instream:
      cols = row.strip("\n").split("\t")
      for col_id, col in enumerate(cols):
        max_widths[col_id] = max(max_widths.get(col_id, 0), len(col))
      yield cols

  instream = process(instream)

  for cols in itertools.chain(
      list(itertools.islice(instream, args.initial)), instream):
    yield " ".join((
        getattr(col, just)(max_widths[col_id])
        for col_id, col in enumerate(cols))) + "\n"

for line in tsv(sys.stdin): sys.stdout.write(line)
