#!/usr/bin/env python2

import sys
import argparse


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('column', nargs='*')
  args = parser.parse_args()

  header = next(sys.stdin).strip("\n")
  lookup = dict(map(tuple, map(reversed, enumerate(header.split("\t")))))

  print "\t".join(args.column)
  for line in sys.stdin:
    fields = line.strip("\n").split("\t")
    parts = [fields[lookup[column]] for column in args.column]
    print "\t".join(parts)


if __name__ == "__main__":
  main()
